# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bex < Formula
  desc "Bobby's XML Utility"
  homepage "https://github.com/soldiermoth/bex"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/soldiermoth/bex/releases/download/v0.0.8/bex_0.0.8_Darwin_arm64.tar.gz"
      sha256 "c6f7dff0ac6b46689ef9a1262e065eceaca00ade7ae872b53fa65792ae7d261e"

      def install
        bin.install "bex"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/soldiermoth/bex/releases/download/v0.0.8/bex_0.0.8_Darwin_x86_64.tar.gz"
      sha256 "b8f0ac1c4258003d6f48f62cc0c9d542ae681daad10e5da6efaaa26ef6b12d62"

      def install
        bin.install "bex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/soldiermoth/bex/releases/download/v0.0.8/bex_0.0.8_Linux_arm64.tar.gz"
      sha256 "499b1b295d5fb628c8fdff0e91646202e302ef1a4a3592c62bd38545c05d70e2"

      def install
        bin.install "bex"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/soldiermoth/bex/releases/download/v0.0.8/bex_0.0.8_Linux_x86_64.tar.gz"
      sha256 "f61f3500d905cfc0286723ad192dc050e99d908cddddea5cbbebbf8204483e13"

      def install
        bin.install "bex"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/soldiermoth/bex/releases/download/v0.0.8/bex_0.0.8_Linux_armv6.tar.gz"
      sha256 "4408c4937056d96b73ac802413643c25b26fdb00c4cd202298108e5e1e9a2eec"

      def install
        bin.install "bex"
      end
    end
  end
end
