# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bex < Formula
  desc "Bobby's XML Utility"
  homepage "https://github.com/soldiermoth/bex"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/soldiermoth/bex/releases/download/v0.0.3/bex_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "775917dadf8daaf078622f8863afba77c04adfe2b28455806851f97787b26163"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/soldiermoth/bex/releases/download/v0.0.3/bex_0.0.3_Linux_x86_64.tar.gz"
    sha256 "872c9c2013f8c3f052b812d5b174cebb5b7443f1e566d55b576abd4409128793"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/soldiermoth/bex/releases/download/v0.0.3/bex_0.0.3_Linux_arm64.tar.gz"
    sha256 "a67e9820d0600922e688f3636242d52ceadb0371dd5ff87dd627bec3c6662308"
  end

  def install
    bin.install "bex"
  end
end
