# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csvx < Formula
  desc "CSV File Utility"
  homepage "https://github.com/soldiermoth/csvx"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/soldiermoth/csvx/releases/download/v0.1.3/csvx_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "1631872bf330ee7bf733da8c58d80b067c6bf29e13fde2319b657917d0b6a908"

      def install
        bin.install "csvx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/soldiermoth/csvx/releases/download/v0.1.3/csvx_0.1.3_Darwin_arm64.tar.gz"
      sha256 "a3ba38a7cef6698aa8c8ddb92ce485c26eee2c49545d15c3c136b4997086c61c"

      def install
        bin.install "csvx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/soldiermoth/csvx/releases/download/v0.1.3/csvx_0.1.3_Linux_arm64.tar.gz"
      sha256 "b664052933e8e2e5a71abbf6c39607c64cdc32bef576bdc3a137baad717d03f1"

      def install
        bin.install "csvx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/soldiermoth/csvx/releases/download/v0.1.3/csvx_0.1.3_Linux_x86_64.tar.gz"
      sha256 "9c781777977f3fcac877f6324d5e8dfc3bc37774732a060bd8a0260f5ffe6f0d"

      def install
        bin.install "csvx"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/soldiermoth/csvx/releases/download/v0.1.3/csvx_0.1.3_Linux_armv6.tar.gz"
      sha256 "12fe65fc4cb8acc43226931c7b2a0a4bf60379ce25c7a1d425478795c2942506"

      def install
        bin.install "csvx"
      end
    end
  end
end
