# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csvx < Formula
  desc "CSV File Utility"
  homepage "https://github.com/soldiermoth/csvx"
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/soldiermoth/csvx/releases/download/v0.1.0/csvx_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "c5f85e0124d79346f3cc07f70d26c34d3ccc72486dfdff44e30b5f834bbd4408"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/soldiermoth/csvx/releases/download/v0.1.0/csvx_0.1.0_Linux_x86_64.tar.gz"
    sha256 "f55c6a5501fe6b0f8b1095da9ddb0f4e2fc0a1806f5008bbbfba8a77fac5a9ce"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/soldiermoth/csvx/releases/download/v0.1.0/csvx_0.1.0_Linux_arm64.tar.gz"
    sha256 "c36d800c64239eff240ed59d5302d3ec0a73ecfde1e5e6c49c6c7b2a24a6cdd5"
  end

  def install
    bin.install "csvx"
  end
end
