# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hlsq < Formula
  desc "Add some color to your HLS manifests"
  homepage "https://github.com/soldiermoth/hlsq"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/soldiermoth/hlsq/releases/download/v0.1.1/hlsq_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "67b4ae5c5b292443e2930bd5a11d663fba592647b516ee4882159ccd901267ea"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/soldiermoth/hlsq/releases/download/v0.1.1/hlsq_0.1.1_Linux_x86_64.tar.gz"
    sha256 "2388c69149a97c6f0c3fb60b6e25769ba95ead3f998c2b98b202a467bcaa2a5c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/soldiermoth/hlsq/releases/download/v0.1.1/hlsq_0.1.1_Linux_arm64.tar.gz"
    sha256 "6c0ee0962684381c5510a1b27a6e2d908836f515f771de24b63a1067d414cd37"
  end

  def install
    bin.install "hlsq"
  end
end
