# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hlsq < Formula
  desc "Add some color to your HLS manifests"
  homepage "https://github.com/soldiermoth/hlsq"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/soldiermoth/hlsq/releases/download/v0.1.2/hlsq_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "71db76065c3a0899aaac6f6c8de2e489c6158f466a1dadba5b32db1b45e4eb7f"

      def install
        bin.install "hlsq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/soldiermoth/hlsq/releases/download/v0.1.2/hlsq_0.1.2_Linux_x86_64.tar.gz"
      sha256 "27b790a677f440281da83ffade0c6c5fa5c69216b1db2dd9f00d64f5e302bb69"

      def install
        bin.install "hlsq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/soldiermoth/hlsq/releases/download/v0.1.2/hlsq_0.1.2_Linux_arm64.tar.gz"
      sha256 "13b9ebd3b1aa8fa46157222ddb0eb9c3fdc65c7adec69257c52f61eeca7b9e4b"

      def install
        bin.install "hlsq"
      end
    end
  end
end
