# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Humanlog < Formula
  desc "Utility for displaying logs in a pretty-fied format"
  homepage "https://github.com/soldiermoth/humanlog"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/soldiermoth/humanlog/releases/download/v0.2.2/humanlog_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "02bb8763133bd9f812746f07b65163f3b41010cbf1b3bc74bfb3e3c62dd914dd"

      def install
        bin.install "humanlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/soldiermoth/humanlog/releases/download/v0.2.2/humanlog_0.2.2_Darwin_arm64.tar.gz"
      sha256 "9e58f38aa567bc0d439a91fad00e8b35cd7c75d246e453862a29c6fdfccc7d99"

      def install
        bin.install "humanlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/soldiermoth/humanlog/releases/download/v0.2.2/humanlog_0.2.2_Linux_arm64.tar.gz"
      sha256 "c6a0f8c6671f3c40d0c9ba2d72b51102000010d787c6e4c9f8b439ff06757b25"

      def install
        bin.install "humanlog"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/soldiermoth/humanlog/releases/download/v0.2.2/humanlog_0.2.2_Linux_armv6.tar.gz"
      sha256 "07d9ba8634b235542a7a57a2e94f28514b346b586f671a8efc532bc0da084e97"

      def install
        bin.install "humanlog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/soldiermoth/humanlog/releases/download/v0.2.2/humanlog_0.2.2_Linux_x86_64.tar.gz"
      sha256 "3ebfb81fcdd4d3f334e1b8bd0292f5c81ede4b2a3b2712619267104c544819cf"

      def install
        bin.install "humanlog"
      end
    end
  end
end
